### PR TITLE
Create lunch menu

### PR DESCRIPTION
**Pull request by NutthanichN**
Add lunch and beverage menu

### CODE REVIEW

**Comment by magmagcup** [comment]
Please add a money currency.

**Comment by th-bunratta** [comment]
Are those of yourselves lunch menus? Not people? Please use a proper form of nouns.

**Comment by NutthanichN** [comment]
Please come review my merge :)

@MaiNorapong
@th-bunratta
@magmagcup
@plumest

**Comment by MaiNorapong** [comment]
I think this is OK to merge. What say you @th-bunratta ?

**Pull request merged**
